version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - backend/.env
    restart: always
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - frontend/.env  # ✅ Pass Vite environment variables
    restart: always
    depends_on:
      - backend  # ✅ Frontend depends on backend
